# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

# Cloudinary
CLOUD_NAME: "djfhtqjzs"
API_KEY: "874249853626169"
API_SECRET: "4ZhO7cjS-KAhFW6JFX4gHSpZm88"

# Default avatar path
DEFAULT_AVATAR_PATH: "/images/:style/default.png"

# Gmail
GMAIL_USERNAME: 'adidasruslan@gmail.com'
GMAIL_PASSWORD: '17d3199F'

# Faye settings
SERVER: "http://localhost:9292/faye"
SECRET_TOKEN: "secret"

production:
  SERVER: "http://example.com/faye"
  SECRET_TOKEN: "be6c8eb6a20eea6b40433e147c2441aa5efe991e17ff1d4d220734b5bb9e8176"
  SIGNATURE_EXPIRATION: 3600