development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"

test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"

production:
  server: "https://private-pub-socket-rails.herokuapp.com/faye"
  secret_token: <%= ENV['PRIVATE_PUB_TOKEN'] %>
  signature_expiration: 3600