# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 346b8ef9639126b90226e558cf8df11e319e6d24e8843c23631372b44097107e8ebb7ef7e2b843becf5215eb1da4133f3e83c1ef126b15d6ee7f1601e8f01e56

test:
  secret_key_base: 98c7c55c70f4b5daef8319781c8f769229121d67606faffec62e8d896bf1087c5b9b3b675566635ab17ff1eab19f8e9e959b0b626475596c13ce7e598c3b6bb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
